export const ADD_FRIEND = "ADD_FRIEND";
export const FETCH_FRIEND = "FETCH_FRIEND";
export const UNFRIEND = "UNFRIEND";
export const ACCEPT = "ACCEPT";
export const GET_LIST_REQUEST_FRIENDS = "GET_LIST_REQUEST_FRIENDS";
export const FETCH_LIST_REQUEST_FRIENDS = "FETCH_LIST_REQUEST_FRIENDS"