export const GET_FRIEND = "ADD_FRIEND";
export const FETCH_FRIEND = "FETCH_FRIEND";
export const UNFRIEND = "UNFRIEND";
export const ACCEPT = "ACCEPT";
export const GET_LIST_REQUEST_FRIENDS = "GET_LIST_REQUEST_FRIENDS";
export const FETCH_LIST_REQUEST_FRIENDS = "FETCH_LIST_REQUEST_FRIENDS"
export const GET_LIST_RECEIVED_FRIENDS = "GET_LIST_RECEIVED_FRIENDS";
export const FETCH_LIST_RECEIVED_FRIENDS = "FETCH_LIST_RECEIVED_FRIENDS"
export const SEND_REQUEST_FRIENDS= "SEND_REQUEST_FRIENDS"

export const ADD_RECEIVED_FRIENDS = "ADD_RECEIVED_FRIENDS"
